### ISSUE TITLE
Getting an exception when trying to use lazy variables

### ISSUE THREAD

**Issue by HussamHallak** [Redempt/Crunch#10]
I tried running the lazy variables usage example in the readme file. I got this exception:

Exception in thread "main" java.lang.NumberFormatException: Non-numeric character in input 'x + 1'
	at redempt.crunch.data.FastNumberParsing.parseDouble(FastNumberParsing.java:85)
	at redempt.crunch.ExpressionCompiler.compileToken(ExpressionCompiler.java:245)
	at redempt.crunch.ExpressionCompiler.compileValue(ExpressionCompiler.java:73)
	at redempt.crunch.ExpressionCompiler.compile(ExpressionCompiler.java:32)
	at redempt.crunch.Crunch.compileExpression(Crunch.java:22)
	at CrunchDemo.main(CrunchDemo.java:10)

**Comment by Redempt** [comment]
Able to reproduce by not supplying the EvaluationEnvironment when compiling the expression. This is an issue on your end. I've added a test case for the exact input and it passes.

**Comment by HussamHallak** [comment]
Thank you.
